### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Mailaender** [flathub/com.mattermost.Desktop#147]
On Fedora 41 I get
```
[2:1120/070003.310983:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket
```

repeatedly and

```
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/run/user/1000/app/com.mattermost.Desktop/.org.chromium.Chromium.WgKrA4'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/main/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/app/main/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Mailaender** [comment]
I checked that. It is unrelated to the selinux flag. Also tried to give it more Flatpak permissions, but that didn't help.

**Comment by Mailaender** [comment]
After a restart it now works so I might just have been the selinux flat. Sorry for the confusion.
