### ISSUE TITLE
quit unexpectitly

### ISSUE THREAD

**Issue by ServerMonkey** [flathub/com.mattermost.Desktop#41]
Get en error after update to Mattermost 5.0.0
"Internal error: Render frame was disposed before WebFrameMain could be accessed"

I'm on Debian 10 Buster with latest updates. Flatpak 1.2.5

Log:
```
Application: Mattermost 5.0.0
Platform: Linux 4.19.0-18-amd64 x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at ViewManager.fadeLoadingScreen (/app/main/resources/app.asar/index.js:60952:40)
    at ViewManager.setServerInitialized (/app/main/resources/app.asar/index.js:60969:16)
    at IpcMainImpl.handleReactAppInitialized (/app/main/resources/app.asar/index.js:60223:24)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)
```

**Comment by ServerMonkey** [comment]
Nop, still the same error:

Application: Mattermost 5.0.1
Platform: Linux 4.19.0-18-amd64 x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at Object.sendToRenderer (/app/main/resources/app.asar/index.js:59963:33)
    at emitMentions (/app/main/resources/app.asar/index.js:64578:17)
    at setSessionExpired (/app/main/resources/app.asar/index.js:64714:3)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/index.js:64720:3)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)

**Comment by lriesebos** [comment]
Same here on Ubuntu 20.04 with Flatpak 1.6.5. Are the mattermost devs aware of this issue? I can't quickly find a similar issue in https://github.com/mattermost/desktop

```
Application: Mattermost 5.0.2
Platform: Linux 5.11.0-40-generic x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at Object.sendToRenderer (/app/main/resources/app.asar/index.js:59967:33)
    at emitMentions (/app/main/resources/app.asar/index.js:64582:17)
    at setSessionExpired (/app/main/resources/app.asar/index.js:64718:3)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/index.js:64724:3)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)
```

**Comment by vchernin** [comment]
@lriesebos if you can't find the same issue in their repo I'd suggest opening a new one. Especially since previous solved issues don't seem to have helped.

**Comment by ServerMonkey** [comment]
I opened an issue here as well: https://github.com/mattermost/desktop/issues/1888

**Comment by gdurif** [comment]
Any news ?

I still get an error "quit unexpectedly" with the current 5.0.2 version.

I get the following logs (that are not always the same, here are two different examples):

```
Application: Mattermost 5.0.2
Platform: Linux 5.11.0-43-generic x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at Object.<anonymous> (/app/main/resources/app.asar/index.js:61689:29)
    at Object.emit (events.js:388:22)
```

```
Application: Mattermost 5.0.2
Platform: Linux 5.11.0-43-generic x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at ViewManager.fadeLoadingScreen (/app/main/resources/app.asar/index.js:60982:40)
    at ViewManager.setServerInitialized (/app/main/resources/app.asar/index.js:60999:16)
    at IpcMainImpl.handleReactAppInitialized (/app/main/resources/app.asar/index.js:60250:24)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)
```

**Comment by SemaiCZE** [comment]
Honestly I don't know, I'm just packaging releases from mattermost/desktop because I want it to be part of flatpak ecosystem. I'd like to help, but I'm not a web developer and it works on my Fedora system. But I'm open to ideas :)

**Comment by vchernin** [comment]
FYI there are recent RC releases: https://github.com/mattermost/desktop/releases

which in theory include the fixes for https://github.com/mattermost/desktop/issues/1888

**Comment by ServerMonkey** [comment]
I upgraded to Debian 11, error is gone there on Mattermost 5.0.2 flatpak, but it was still present in Debian 10 with the same version.

But I tested mattermost-desktop-5.0.3-rc1-linux-amd64.deb on a Debian 10 VM, and there are no more errors. Works as expected. But then I did not test it with the flatpak dependencies so...

**Comment by SemaiCZE** [comment]
@ServerMonkey can you try this build `flatpak install https://dl.flathub.org/build-repo/72845/com.mattermost.Desktop.flatpakref`? It's 5.0.3-rc1, but I haven't tested it myself yet.

**Comment by gdurif** [comment]
After a recent system update (on my Ubuntu 20.04 system), the version 5.0.2 is now working (I did not find the time to investigate which updated package(s) was the reason it now works though).

**Comment by vchernin** [comment]
5.0.3 is now merged here, please retest with it if anyone is still experiencing this.

**Comment by bluewww** [comment]
The bug is still hapening for me

**Comment by gdurif** [comment]
@bluewww which Linux version are you using ?

On my Ubuntu (20.04), the problem comes back from time to time and it is generally solved by a system update (e.g. with `apt-get update && apt-get upgrade` on my system)

**Comment by bluewww** [comment]
Centos 7.9.2009

**Comment by ServerMonkey** [comment]
> 5.0.3 is now merged here, please retest with it if anyone is still experiencing this.
5.0.4 Works still fine on Debian 10 and 11. I did a test on the same VM and same Debian 10 version (without apt upgrade)
I only ran 'flatpak update'.
Which also updated:
org.freedesktop.Platform
org.freedesktop.Platform.GL.default
org.freedesktop.Platform.Locale
org.freedesktop.Platform.Desktop

@bluewww @gdurif
You could try to create a VM of the same version of your os. Install the same version of flatpak and Mattermost.
See if the bug is still present there.

**Comment by gdurif** [comment]
@ServerMonkey version 5.0.4 works fine for me on an up-to-date Ubuntu 20.04.4 LTS

**Comment by jf99** [comment]
Still an issue in version 5.0.4 on Ubuntu 20.04 LTS.

**Comment by jf99** [comment]
@SemaiCZE Yes, the tray icon is visible during startup before the crash happens. I don't see a way to disable it without starting mattermost. In the meantime however, I moved to another computer with Ubuntu 22.04 where this problem does not happen.
